[package]
name = "roti"
version = "0.1.0"
edition = "2024"

[dependencies]
bson = "2.14.0"
choki = "1.1.4"
dotenv = "0.15.0"
rand = "0.9.0"
serde = "1.0.219"
serde_json = "1.0"
[dependencies.mongodb]
version = "3.2.3"
features = ["sync"]
